version: '3.8'

services:
    redis_db:
        image: 'redis:alpine'
        hostname: redis
        restart: always
        volumes:
            - redis_data:/data

    djangok8s:
        image: djangok8s
        build:
            context: .
            dockerfile: Dockerfile.djangok8s
        environment:
            - PORT=8000
        env_file:
            - .env.prod
        expose:
            - 8000
        restart: always

    celery:
        image: djangok8s
        build:
            context: .
            dockerfile: Dockerfile.djangok8s
        env_file:
            - .env
        command: "celery -A web_k8s worker --beat -l info"
        depends_on:
            - djangok8s
            - redis_db
        restart: always


volumes:
    redis_data:
