# Deployments

apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangok8s-deployment
  namespace: djangok8s
  labels:
    app: djangok8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: djangok8s-deployment
  template:
    metadata:
      labels:
        app: djangok8s-deployment
    spec:
      containers:
      - name: django-k8s
        image: yllorca/django-k8s:latest
        envFrom:
          - secretRef:
              name: djangok8s-prod-env
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: djangok8s
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes: # Esta línea se ha movido a estar dentro de spec.template.spec
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: djangok8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery
        image: yllorca/django-k8s:latest
        command: ["celery"]
        args: ["-A", "web_k8s", "worker", "--beat", "-l", "info"]
        envFrom:
        - secretRef:
            name: djangok8s-prod-env

---

# Services

apiVersion: v1
kind: Service
metadata:
  name: djangok8s-service
  namespace: djangok8s
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: djangok8s-deployment

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: djangok8s
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis

---

# Persistent Storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: djangok8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

