apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangok8s-deployment
  labels:
    app: djangok8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: djangok8s-deployment
  template:
    metadata:
      labels:
        app: djangok8s-deployment
    spec:
      containers:
      - name: django-k8s
        image: yllorca/django-k8s:latest
        envFrom:
          - secretRef:
              name: djangok8s-prod-env
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: djangok8s-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: djangok8s-deployment
