name: Django Tests and Docker Build & Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django:
    uses: yllorca/djangok8s/.github/workflows/django-test.yaml@main

  container_builder:
    needs: [test_django]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yllorca/django-k8s:latest
          file: Dockerfile.djangok8s # Especifica el nombre de tu Dockerfile personalizado aquí
